# Generated by Django 2.2.7 on 2019-11-16 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_page_sections'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sections',
            new_name='Section',
        ),
    ]
